name: Build file transfer

on: workflow_dispatch

jobs:
  file-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metadata
        id: gen_meta
        run: |
          SHORTHASH=$(git rev-parse --short HEAD)
          echo "**** Setting build date to $BUILD_DATE ****"
          echo ::set-output name=sub_sha::${SHORTHASH}
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/A2va/f-transfer
          labels: |
            org.opencontainers.image.title=f-transfer
            org.opencontainers.image.description="https://github.com/A2va/dai-f-transfer"
            org.opencontainers.image.vendor=A2va
            org.opencontainers.image.source="https://github.com/A2va/dai-f-transfer"
            org.opencontainers.image.version="${{ steps.gen_meta.outputs.sub_sha }}"
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.gen_meta.outputs.sub_sha }}
          flavor: |
            prefix=f-transfer,onlatest=true  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: A2va
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ghcr.io/A2va/file-transfer:latest
